# Generated by Django 3.2.25 on 2024-03-09 08:12

from django.db import migrations
from django.contrib.auth.models import User
from ..models import Account, SupportTicket, SupportTicketReply


def insert_dummy_accounts(apps, schema_editor):
    accounts = []
    for i in range(1, 21):
        accounts.append(
            {'username': f'Stephani user{i}', 'email': f'user{i}@example.com', 'password': f'password{i}'}
        )
    for account in accounts:
        Account.objects.create(**account)


def insert_support_ticket(apps, schema_editor):
    support_tickets = []
    for i in range(1, 21):
        account = Account.objects.get_or_create(username=f'Stephani user{i}')[0]
        support_tickets.append(
            {'title': f'Support Ticket {i}', 'description': f'Description of support ticket {i}', 'account': account}
        )
    for ticket in support_tickets:
        SupportTicket.objects.create(**ticket)


def insert_support_ticket_reply(apps, schema_editor):
    support_ticket_replies = []
    for i in range(5, 11):
        account = Account.objects.get_or_create(username=f'Stephani user{i - 3}')[0]
        support_ticket = SupportTicket.objects.get_or_create(title=f'Support Ticket {i+3}')[0]
        support_ticket_replies.append(
            {'account': account, 'support_ticket': support_ticket}
        )
    for reply in support_ticket_replies:
        SupportTicketReply.objects.create(**reply)


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial')
    ]

    operations = [
        migrations.RunPython(insert_dummy_accounts),
        migrations.RunPython(insert_support_ticket),
        migrations.RunPython(insert_support_ticket_reply),
    ]
